// Domain types live in @/types (single source of truth). Re-exported here
// so existing `import { Product } from "@/lib/data"` call sites keep working.
import type {
  Product,
  Category,
  SubscriptionBox,
  Testimonial,
  JournalArticle,
  Maker,
  FaqItem,
  SeoConfig,
  ShopSettings,
  NewsletterConfig,
} from "@/types";

export type {
  Product,
  Category,
  SubscriptionBox,
  Testimonial,
  JournalArticle,
  Maker,
  FaqItem,
  SeoConfig,
  ShopSettings,
  NewsletterConfig,
};

export const products: Product[] = [
  {
    id: "kangra-orthodox-black",
    name: "Kangra Orthodox Black Tea",
    category: "tea",
    categoryLabel: "Tea",
    originDistrict: "Kangra",
    price: 499,
    weight: "100g",
    shortDescription: "Full-bodied black tea with malt and dried fruit notes from Kangra Valley.",
    description: "Full-bodied black tea from the mist-covered slopes of Kangra Valley. Hand-plucked and orthodox processed to preserve the leaf's natural character. Notes of malt and dried fruit with a smooth, lingering finish.",
    whyWeSelected: "This tea represents the finest expression of Kangra's orthodox tradition. The hand-rolling technique creates a leaf that unfurls beautifully in the cup, releasing layers of flavour that machine-processed teas simply cannot match.",
    regionStory: "Kangra Valley has been producing tea since the mid-19th century, when British planters recognised the Dhauladhar range's unique climate. Today, smallholder growers continue this legacy, tending bushes at elevations where cool mist and mineral-rich soil create teas of remarkable depth.",
    image: "/images/tea-black.jpg",
    galleryImages: [],
    badge: "Spring Harvest",
    traceability: { harvest: "Spring 2026", estate: "Kangra Valley", elevation: "1,420 m", craft: "Orthodox", batch: "KT260301" },
    origin: "Sourced from small tea gardens across Kangra Valley, Himachal Pradesh. Each batch is hand-rolled and sun-dried using traditional methods passed down through generations.",
    ingredients: ["100% Camellia sinensis leaves"],
    attributes: ["100g", "Vegetarian", "Spring Harvest", "Orthodox"],
    howToEnjoy: ["Use 2g per 200ml of water at 90-95°C", "Steep for 3-4 minutes for full body", "Excellent with a splash of milk or enjoyed plain", "Pairs beautifully with morning toast or afternoon biscuits"],
    storage: "Store in an airtight container away from light, moisture, and strong odours. Our tins are designed for this purpose. For optimal freshness, consume within 12 months of the harvest date printed on each tin.",
    shippingNote: "Shipped in protective packaging from Palampur, Himachal Pradesh. Free delivery on orders above ₹1,000.",
    inStock: true,
    featured: true,
    showInShop: true,
    subscriptionEligible: true,
    subscriptionPlans: ["essential", "family", "seasonal", "signature"],
    slug: "kangra-orthodox-black",
    relatedProducts: ["kangra-green-tea", "wild-forest-honey"],
    displayOrder: 1,
    status: "active",
  },
  {
    id: "kangra-green-tea",
    name: "Kangra Green Tea",
    category: "tea",
    categoryLabel: "Tea",
    originDistrict: "Kangra",
    price: 549,
    weight: "100g",
    shortDescription: "Delicate green tea with vegetal notes and a hint of sweetness from Kangra.",
    description: "Delicate and refreshing green tea with vegetal notes and a hint of sweetness. Minimal oxidation preserves the fresh, grassy character of the Kangra terroir.",
    whyWeSelected: "Kangra green tea is a hidden gem — pan-fired rather than steamed, giving it a toasty warmth that balances its natural freshness. This is the tea we reach for on quiet afternoons.",
    regionStory: "Grown in the cool, misty climate of Kangra Valley where the Dhauladhar range creates the perfect conditions for slow-growing, flavourful tea leaves. The pan-firing tradition here predates modern processing methods.",
    image: "/images/tea-green.jpg",
    galleryImages: [],
    badge: "Handcrafted",
    traceability: { harvest: "Spring 2026", estate: "Kangra Valley", elevation: "1,380 m", craft: "Pan-Fired", batch: "KT260302" },
    origin: "Grown in the cool, misty climate of Kangra Valley where the Dhauladhar range creates the perfect conditions for slow-growing, flavourful tea leaves.",
    ingredients: ["100% Green tea leaves"],
    attributes: ["100g", "Vegetarian", "Handcrafted", "Pan-Fired"],
    howToEnjoy: ["Use 2g per 200ml of water at 75-80°C — cooler water preserves the delicate flavours", "Steep for 2-3 minutes; longer steeping brings out more body", "Best enjoyed plain to appreciate its vegetal character", "A wonderful companion to light meals and salads"],
    storage: "Store in an airtight container away from light, moisture, and strong odours. Our tins are designed for this purpose. For optimal freshness, consume within 12 months of the harvest date printed on each tin.",
    shippingNote: "Shipped in protective packaging from Palampur, Himachal Pradesh. Free delivery on orders above ₹1,000.",
    inStock: true,
    featured: false,
    showInShop: true,
    subscriptionEligible: true,
    subscriptionPlans: ["essential", "family", "seasonal", "signature"],
    slug: "kangra-green-tea",
    relatedProducts: ["kangra-orthodox-black", "wild-forest-honey"],
    displayOrder: 2,
    status: "active",
  },
  {
    id: "wild-forest-honey",
    name: "Himalayan Wild Forest Honey",
    category: "honey",
    categoryLabel: "Honey",
    originDistrict: "Chamba",
    price: 449,
    weight: "250g",
    shortDescription: "Raw, unfiltered honey from wild Himalayan forests with complex floral notes.",
    description: "Raw, unfiltered honey collected from wild bee colonies in the Himalayan forests. Dark, rich, and complex with notes of wildflowers and tree resin.",
    whyWeSelected: "This honey is as close to the forest as you can get without climbing the trees yourself. Raw, unheated, and unfiltered — every jar carries the fingerprint of a specific bloom season in a specific forest.",
    regionStory: "The upper Himalayan forests around Bir and Chamba are home to wild Apis dorsata colonies that follow the rhododendron and wildflower blooms. Traditional beekeepers have harvested here for generations, taking only what the colonies can spare.",
    image: "/images/honey-wild.jpg",
    galleryImages: [],
    badge: "Raw & Unfiltered",
    traceability: { harvest: "Spring 2026", estate: "Himalayan Forests", elevation: "2,100 m", craft: "Wild Harvested", batch: "HW260101" },
    origin: "Collected by traditional beekeepers from wild Apis dorsata colonies in the upper Himalayan forests. Never heated or filtered.",
    ingredients: ["100% Raw Himalayan honey"],
    attributes: ["250g", "Vegetarian", "Raw & Unfiltered", "Wild Harvested"],
    howToEnjoy: ["Stir a spoonful into warm water or tea — never boiling, to preserve the enzymes", "Drizzle over toast, yoghurt, or seasonal fruit", "Use as a natural sweetener in baking and marinades", "A teaspoon before bed is a mountain tradition"],
    storage: "Store at room temperature in a dry place. Crystallisation is natural and a sign of purity — gently warm the jar in sunlight or warm water to return to liquid form. Do not refrigerate.",
    shippingNote: "Shipped in protective packaging from Palampur, Himachal Pradesh. Free delivery on orders above ₹1,000.",
    inStock: true,
    featured: false,
    showInShop: true,
    subscriptionEligible: true,
    subscriptionPlans: ["essential", "family", "seasonal", "signature"],
    slug: "wild-forest-honey",
    regionImage: "/images/regions/chamba.jpg",
    relatedProducts: ["kangra-orthodox-black", "seasonal-fruit-preserve"],
    displayOrder: 3,
    status: "active",
  },
  {
    id: "wild-plum-preserve",
    name: "Seasonal Fruit Preserve",
    category: "preserves",
    categoryLabel: "Fruit Preserves",
    originDistrict: "Mandi",
    price: 349,
    weight: "200g",
    shortDescription: "Small-batch wild plum preserve crafted by women-led SHGs in Himachal.",
    description: "Small-batch fruit preserves crafted by women-led SHGs across Himachal Pradesh. The fruit changes with the season—plum, apricot, peach, apple, or pear—but the care and craftsmanship remain the same.",
    whyWeSelected: "These preserves capture something no factory can replicate — the patience of slow cooking and the discernment of women who have been preserving fruit their entire lives. Each jar tastes like a specific afternoon in a specific kitchen.",
    regionStory: "Wild plums grow along the forest edges of Mandi and Kullu districts, where women have foraged and preserved them for generations. The SHGs we partner with turn this household knowledge into a livelihood, one jar at a time.",
    image: "/images/preserve-plum.jpg",
    galleryImages: [],
    badge: "SHG Crafted",
    traceability: { harvest: "Summer 2026", estate: "Himalayan Foothills", elevation: "1,200 m", craft: "Slow-Cooked", batch: "FP260101" },
    origin: "Wild plums are foraged from the forest edges by women from Self Help Groups in rural Himachal. Each jar is cooked in small batches over wood fires.",
    ingredients: ["Wild plums", "Raw sugar", "Cinnamon", "Lemon juice"],
    attributes: ["200g", "Vegetarian", "SHG Crafted", "No Preservatives"],
    howToEnjoy: ["Spread generously on toast, parathas, or crackers", "Swirl into yoghurt or oatmeal for a fruity breakfast", "Use as a filling for pastries and thumbprint cookies", "Pair with sharp cheese for an unexpected appetiser"],
    storage: "Refrigerate after opening and consume within 4 weeks. Unopened jars keep for up to 12 months in a cool, dark cupboard. A clean, dry spoon helps preserve freshness.",
    shippingNote: "Shipped in protective packaging from Palampur, Himachal Pradesh. Free delivery on orders above ₹1,000.",
    inStock: true,
    featured: false,
    showInShop: true,
    subscriptionEligible: true,
    subscriptionPlans: ["essential", "family", "seasonal", "signature"],
    slug: "seasonal-fruit-preserve",
    regionImage: "/images/regions/mandi.jpg",
    relatedProducts: ["wild-forest-honey", "traditional-himalayan-pickle"],
    displayOrder: 4,
    status: "active",
  },
  {
    id: "galgal-pickle",
    name: "Traditional Himalayan Pickle",
    category: "pickles",
    categoryLabel: "Traditional Pickles",
    originDistrict: "Kangra",
    price: 279,
    weight: "200g",
    shortDescription: "Sun-cured hill lemon pickle made by women-led SHGs using traditional recipes.",
    description: "Traditional pickles handcrafted by women-led SHGs across Himachal Pradesh. Ingredients change with the seasons while preserving authentic family recipes.",
    whyWeSelected: "This pickle carries the authority of generations. The galgal — a citrus native to these hills — is sun-cured and pickled using recipes that haven't changed because they didn't need to. It is sharp, fragrant, and unmistakably Himalayan.",
    regionStory: "Galgal (Citrus pseudolimon) is native to the Himalayan foothills of Kangra and Mandi. SHG women sun-cure the fruit during the winter months, then pickle it with mustard oil and mountain spices using recipes passed down unchanged for generations.",
    image: "/images/pickle-galgal.jpg",
    galleryImages: [],
    badge: "Traditional Recipe",
    traceability: { harvest: "Winter 2025", estate: "Kangra Valley", elevation: "1,400 m", craft: "Sun-Cured", batch: "TP260201" },
    origin: "Galgal (Citrus pseudolimon) is native to the Himalayan foothills. These are sun-cured and pickled by SHG women using recipes unchanged for generations.",
    ingredients: ["Hill lemon", "Green chilli", "Mustard oil", "Fenugreek", "Nigella seeds", "Turmeric"],
    attributes: ["200g", "Vegetarian", "Traditional Recipe", "Sun-Cured"],
    howToEnjoy: ["Serve alongside dal-rice, parathas, or any Indian meal", "A small spoonful adds brightness to sandwiches and wraps", "Chop finely and mix into yoghurt for a quick raita", "Use as a tangy topping for grilled vegetables or meats"],
    storage: "Store in a cool, dry place. Refrigeration extends shelf life but is not required. Always use a clean, dry spoon. Best consumed within 12 months of opening.",
    shippingNote: "Shipped in protective packaging from Palampur, Himachal Pradesh. Free delivery on orders above ₹1,000.",
    inStock: true,
    featured: false,
    showInShop: true,
    subscriptionEligible: true,
    subscriptionPlans: ["essential", "family", "seasonal", "signature"],
    slug: "traditional-himalayan-pickle",
    regionImage: "/images/regions/kangra.jpg",
    relatedProducts: ["seasonal-fruit-preserve", "kangra-orthodox-black"],
    displayOrder: 5,
    status: "active",
  },
];

export const categories = [
  { id: "tea", label: "Tea", count: 2 },
  { id: "honey", label: "Honey", count: 1 },
  { id: "preserves", label: "Fruit Preserves", count: 1 },
  { id: "pickles", label: "Traditional Pickles", count: 1 },
] as const;

// ============================================================
// SUBSCRIPTION BOXES
// ============================================================
export const subscriptionBoxes: SubscriptionBox[] = [
  {
    id: "essential",
    name: "Essential Pantry",
    subtitle: "A gentle start",
    price: 599,
    frequency: "Month",
    itemCount: "3–4 items",
    description: "A gentle introduction to the valley — tea and one seasonal pantry staple.",
    contents: [
      "1 x Kangra Orthodox Black Tea (100g)",
      "1 x Seasonal Pantry Staple (honey or preserve)",
      "1 x Tasting Note Card",
    ],
    perks: ["Free delivery", "Pause anytime"],
    ctaText: "Subscribe",
    isVisible: true,
    displayOrder: 1,
  },
  {
    id: "family",
    name: "Family Pantry",
    subtitle: "Our most popular",
    price: 899,
    frequency: "Month",
    itemCount: "5–6 items",
    description: "Our most-loved teas alongside honey and preserves from partner SHGs.",
    contents: [
      "1 x Kangra Orthodox Black Tea (100g)",
      "1 x Kangra Green Tea (100g)",
      "1 x Himalayan Wild Forest Honey (250g)",
      "1 x Seasonal Preserve (200g)",
      "1 x Tasting Note Card",
    ],
    perks: ["Free delivery", "Pause anytime", "Swap any item"],
    badge: "Most Popular",
    featured: true,
    ctaText: "Subscribe",
    isVisible: true,
    displayOrder: 2,
  },
  {
    id: "seasonal",
    name: "Seasonal Pantry",
    subtitle: "A fuller table",
    price: 1199,
    frequency: "Month",
    itemCount: "7–8 items",
    description: "A fuller table — tea, honey, pickles and preserves in generous measure.",
    contents: [
      "1 x Kangra Orthodox Black Tea (100g)",
      "1 x Kangra Green Tea (100g)",
      "1 x Himalayan Wild Forest Honey (250g)",
      "1 x Seasonal Preserve (200g)",
      "1 x Traditional Himalayan Pickle (200g)",
      "1 x Tasting Note Card",
      "1 x Seasonal Recipe Card",
    ],
    perks: ["Free delivery", "Pause anytime", "Swap any item", "10% member pricing"],
    ctaText: "Subscribe",
    isVisible: true,
    displayOrder: 3,
  },
  {
    id: "signature",
    name: "Signature Pantry",
    subtitle: "The complete table",
    price: 1499,
    frequency: "Month",
    itemCount: "9–10 items",
    description: "The complete Palum Dhara table, including limited and single-batch harvests.",
    contents: [
      "1 x Kangra Orthodox Black Tea (100g)",
      "1 x Kangra Green Tea (100g)",
      "1 x Himalayan Wild Forest Honey (250g)",
      "1 x Seasonal Preserve (200g)",
      "1 x Traditional Himalayan Pickle (200g)",
      "1 x Limited Harvest Item (seasonal)",
      "1 x Tasting Note Card",
      "1 x Seasonal Recipe Card",
      "1 x Maker Story Card",
    ],
    perks: ["Free delivery", "Pause anytime", "Swap any item", "15% member pricing", "Early access to limited harvests"],
    badge: "Best Value",
    ctaText: "Subscribe",
    isVisible: true,
    displayOrder: 4,
  },
];

// Testimonials intentionally empty at launch. Do not populate with invented
// names or quotes — add only real customer reviews once they exist.
// A brand newly launching with zero reviews reads as more honest than
// fabricated ones. Revisit this section after the first real orders ship.
export const testimonials: Testimonial[] = [];

// ============================================================
// JOURNAL ARTICLES
// ============================================================
export const journalArticles: JournalArticle[] = [
  {
    id: "life-of-a-tea-leaf",
    title: "The Life of a Kangra Tea Leaf",
    excerpt: "From hand-pluck to hand-roll — a walk through the orthodox process that shaped a valley's reputation.",
    topic: "Tea",
    readTime: "6 min read",
    thumbnail: "/images/tea-green.jpg",
  },
  {
    id: "forest-honey-season",
    title: "Reading the Forest: How Honey Season Begins",
    excerpt: "Wild rhododendron blooms first. What follows is a short, closely watched harvest.",
    topic: "Honey",
    readTime: "5 min read",
    thumbnail: "/images/honey-wild.jpg",
  },
  {
    id: "women-behind-the-jar",
    title: "The Women Behind the Jar",
    excerpt: "Inside the self-help groups turning household recipes into a mountain pantry.",
    topic: "SHGs",
    readTime: "7 min read",
    thumbnail: "/images/story/produce-basket.jpg",
  },
];

// ============================================================
// MAKERS
// ============================================================
export const makers: Maker[] = [
  {
    id: "kangra-tea-growers",
    name: "The Kangra Tea Growers' Collective",
    village: "Palampur, Kangra Valley",
    role: "Tea",
    story: "A cooperative of smallholder growers continuing a tradition of orthodox tea-making that dates back generations in the Dhauladhar foothills.",
    makerImage: "/images/regions/kangra.jpg",
  },
  {
    id: "sundarnagar-shg",
    name: "Sundarnagar Women's Self-Help Group",
    village: "Sundarnagar, Mandi",
    role: "Preserves & Pickles",
    story: "Twelve women turning seasonal fruit and mountain vegetables into small-batch preserves, using recipes passed down through their households.",
    makerImage: "/images/regions/mandi.jpg",
  },
  {
    id: "dhauladhar-beekeepers",
    name: "Dhauladhar Beekeepers' Cooperative",
    village: "Bir, Kangra",
    role: "Honey",
    story: "Forest-based beekeepers following the bloom across the hillside, harvesting raw honey in small, carefully timed batches.",
    makerImage: "/images/regions/chamba.jpg",
  },
];

// ============================================================
// FAQS
// ============================================================
export const faqs: FaqItem[] = [
  {
    question: "Do you offer Cash on Delivery?",
    answer: "Yes. We offer Cash on Delivery (COD) across India. For prepaid orders, we offer an additional 5% discount. Free delivery on all orders above ₹1000.",
  },
  {
    question: "How long does shipping take?",
    answer: "Orders are dispatched within 24-48 hours from Palampur, Himachal Pradesh. Delivery typically takes 3-7 business days depending on your location. You'll receive tracking details via WhatsApp and email.",
  },
  {
    question: "What is your return policy?",
    answer: "We offer a no-questions-asked return policy within 7 days of delivery. If you're not satisfied with your purchase, contact us on WhatsApp and we'll arrange a pickup. For food safety, opened consumables are not eligible for return, but we will issue a full refund regardless.",
  },
  {
    question: "Are your products really from the Himalayas?",
    answer: "Every product includes traceability details — harvest date, estate name, elevation, and batch number. Our tea comes from Kangra Valley, honey from Himalayan forests, and preserves and pickles from women-led SHGs across Himachal Pradesh. We source directly, not through intermediaries.",
  },
  {
    question: "When will The Himalayan Pantry membership launch?",
    answer: "We're planning to launch The Himalayan Pantry in late 2026, after we've built relationships with our first customers and understand what you love most. Join the waitlist to be among the first 500 members and receive early access pricing.",
  },
  {
    question: "How should I store the tea?",
    answer: "Store in an airtight container away from light, moisture, and strong odours. Our tins are designed for this purpose. For optimal freshness, consume within 12 months of the harvest date printed on each tin.",
  },
];

// ============================================================
// NEWSLETTER
// ============================================================
export const newsletterConfig: NewsletterConfig = {
  visible: true,
  heading: "Stay Connected",
  description: "Be the first to know about seasonal harvests, new products and stories from Himachal Pradesh.",
  placeholder: "Your email",
  buttonText: "Subscribe",
};

export const shopSettings: ShopSettings = {
  visible: true,
  displayOrder: 1,
  title: "Shop",
  heading: "Curated Foods from Himachal Pradesh",
  description: "Every product is carefully sourced from trusted growers, artisans and women-led self-help groups across Himachal Pradesh. From Kangra tea to Chamba honey and traditional preserves, each product reflects the region where it is best made.",
  searchPlaceholder: "Search tea, honey, Chamba...",
  sortOptions: ["Featured", "Newest", "Price: Low to High", "Price: High to Low"],
  emptyState: {
    message: "We haven't added products in this category yet.",
    subMessage: "Explore our complete collection instead.",
    cta: "View All Products",
  },
  seo: {
    title: "Shop — Curated Foods from Himachal Pradesh | Palum Dhara",
    description: "Browse our collection of Kangra tea, Himalayan wild honey, fruit preserves and traditional pickles. Sourced directly from growers and women-led SHGs.",
    ogImage: "/images/hero-kangra-valley.jpg",
  },
};
